"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import asyncio
import mimetypes
import os
import sys
from datetime import timedelta
from pathlib import Path

from decouple import Csv, config
from django.urls import reverse_lazy
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-9i!5+efr3q)-=7aoir4p(d^m#3w@4_b-8&7b+1gjq*15pc0zw!",
)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)
# allowed hosts that project would respond to them
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())
# csrf trusted origins
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
# login url
LOGIN_URL = config("LOGIN_URL", default="/")


# check that we are in testing mode or not
def testing_env() -> bool:
    res = (
        "PYTEST_VERSION" in os.environ
        or "PYTEST_CURRENT_TEST" in os.environ
        or os.environ.get("_PYTEST_RAISE", "") != ""
        or any(
            token in sys.argv
            for token in ("test", "pytest", "py.test", "vscode_pytest")
        )
        or os.environ.get("DJANGO_SETTINGS_MODULE", "").endswith("test_settings")
        or any("pytest" in arg.lower() for arg in sys.argv)
        or any(
            "test" in arg.lower() and "manage.py" not in " ".join(sys.argv)
            for arg in sys.argv
        )
    )
    return res


TESTING = lazy(testing_env, bool)
# debug toolbar status
SHOW_DEBUG_TOOLBAR = config("SHOW_DEBUG_TOOLBAR", default=False, cast=bool)

# Application definition

DJANGO_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "modeltranslation",
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "django_filters",
    "channels",
    "django_celery_results",
    "django_js_reverse",
    "rosetta",
    "parsley",
    "ninja",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
]

LOCAL_APPS = [
    # shared application contains all base features
    "shared.infrastructure",
    # core application that has core functionalities
    "core.infrastructure",
    # identity bounded context
    "identity.infrastructure",
    # media bounded context
    "media.infrastructure",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "core.infrastructure.middlewares.locale.ForceIgnoreDefaultLanguageMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.infrastructure.middlewares.host.MultipleProxyMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

# configuration of wsgi and asgi
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# number of threads for threadpool in asgi webserver like daphne
# Optimized for high concurrency: increase thread pool for I/O operations
ASYNC_THREADS = config("ASYNC_THREADS", default=int(os.cpu_count() or 1) * 4, cast=int)

# configure eventloop policy for windows platform
if sys.platform == "win32" and hasattr(asyncio, "WindowsProactorEventLoopPolicy"):
    asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())


# Channel Layers Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DATABASE_NAME", default="imps_new_framework_db"),
        "USER": config("DATABASE_USER", default="root"),
        "PASSWORD": config("DATABASE_PASSWORD", default="admin"),
        "HOST": config("DATABASE_HOST", default="127.0.0.1"),
        "PORT": (
            config("DATABASE_PORT", default="6432")
            if not TESTING()
            else config("TEST_DATABASE_PORT", default="5432")
        ),  # PgBouncer port
        "OPTIONS": {
            # PgBouncer-specific options for high concurrency
            "application_name": config(
                "DATABASE_OPTIONS_APPLICATION_NAME", default="django_imps_framework"
            ),
            "connect_timeout": config(
                "DATABASE_OPTIONS_CONNECTION_TIMEOUT", default=5, cast=int
            ),
            "keepalives": config("DATABASE_OPTIONS_KEEP_ALIVES", default=1, cast=int),
            "keepalives_idle": config(
                "DATABASE_OPTIONS_KEEP_ALIVES_IDLE", default=30, cast=int
            ),
            "keepalives_interval": config(
                "DATABASE_OPTIONS_KEEP_ALIVES_INTERVAL", default=10, cast=int
            ),
            "keepalives_count": config(
                "DATABASE_OPTIONS_KEEP_ALIVES_COUNT", default=5, cast=int
            ),
        },
        # Connection pooling settings optimized for PgBouncer
        # Keep a short-lived persistent connection to reduce ephemeral port churn on Windows
        "CONN_MAX_AGE": config("DATABASE_CONN_MAX_AGE", default=60, cast=int),
        "CONN_HEALTH_CHECKS": config(
            "DATABASE_CONN_HEALTH_CHECKS", default=True, cast=bool
        ),
        # PgBouncer does not support server-side cursors reliably
        "DISABLE_SERVER_SIDE_CURSORS": config(
            "DATABASE_DISABLE_SERVER_SIDE_CURSORS", default=True, cast=bool
        ),
        # Additional settings for high concurrency
        "ATOMIC_REQUESTS": config(
            "DATABASE_ATOMIC_REQUESTS", default=False, cast=bool
        ),  # Disable for better performance with PgBouncer
    }
}


AUTH_USER_MODEL = "identity_infrastructure.User"
LOGIN_URL = reverse_lazy("identity:auth:login")

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

MIGRATIONS_HISTORY_PATH = config(
    "MIGRATIONS_HISTORY_PATH", default="migrations_history", cast=str
)
MIGRATION_MODULES = {}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = (("en", _("English")), ("fa", _("Persian")))

MODELTRANSLATION_LANGUAGES = ("fa", "en")
MODELTRANSLATION_FALLBACK_LANGUAGES = ("fa", "en")
MODELTRANSLATION_AUTO_POPULATE = False

ROSETTA_LANGUAGES = [("fa", _("Persian")), ("en", _("English"))]
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_MESSAGES_PER_PAGE = 20
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = True
ROSETTA_ACCESS_CONTROL_FUNCTION = lambda user: user.is_superuser

LANGUAGE_CODE = config("LANGUAGE_CODE", default="fa")
MULTILANGUAGE_URL_PREFIX = config("MULTILANGUAGE_URL_PREFIX", default=False, cast=bool)
TIME_ZONE = config("TIME_ZONE", default="UTC")
USE_I18N = config("USE_I18N", default=True, cast=bool)
USE_TZ = config("USE_TZ", default=True, cast=bool)


# Auto-discover locale paths for all local apps
def get_auto_locale_paths():
    """Automatically discover locale paths for all LOCAL_APPS"""
    locale_paths = []

    for app in LOCAL_APPS:
        # Convert app name to path (e.g., "core.infrastructure" -> "core")
        app_base = app.split(".")[0]
        locale_path = BASE_DIR / app_base / "locale"

        # Only add if the directory exists
        if locale_path.exists():
            locale_paths.append(str(locale_path))

    # Add config locale path if it exists
    config_locale_path = BASE_DIR / "config" / "locale"
    if config_locale_path.exists():
        locale_paths.append(str(config_locale_path))

    return locale_paths


LOCALE_PATHS = get_auto_locale_paths()


# Static files (CSS, JavaScript, Images)
STATIC_URL = config("STATIC_URL", default="/static/")
STATIC_ROOT = config(
    "STATIC_ROOT", default=os.path.join(BASE_DIR.parent, "cdn", "static")
)
STATICFILES_DIRS = [BASE_DIR / "static"]

# configure media
MEDIA_URL = config("MEDIA_URL", default="/media/")
MEDIA_ROOT = config("MEDIA_ROOT", default=os.path.join(BASE_DIR.parent, "cdn", "media"))

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="self")
mimetypes.add_type("application/javascript", ".js", True)

# Celery Configuration
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Django REST Framework configuration
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "shared.infrastructure.views.exceptions.drf_custom_exception_handler",
}

# Cache configuration for high performance
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config(
            "CACHES_DEFAULT_REDIS_URL", default="redis://localhost:6379/0"
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
            "COMPRESSOR": "django_redis.compressors.zstd.ZStdCompressor",
        },
        # Additional optimizations for your scale:
        "CONNECTION_POOL_KWARGS": {
            "max_connections": 50,  # Handle 200 concurrent users
            "retry_on_timeout": True,
            "socket_connect_timeout": 5,
            "socket_timeout": 5,
        },
        # Serializer optimization for large JSON
        "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        # Connection pooling for high concurrency
        "PARSER_CLASS": "redis.connection.HiredisParser",
        "KEY_PREFIX": "imps_framework",
        "TIMEOUT": config("CACHES_DEFAULT_REDIS_TIMEOUT", cast=int, default=300),
    },
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config(
            "CACHES_SESSIONS_REDIS_URL", default="redis://localhost:6379/1"
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.lz4.Lz4Compressor",
        },
        "KEY_PREFIX": "imps_framework_session",
        "TIMEOUT": config("CACHES_SESSIONS_REDIS_TIMEOUT", cast=int, default=1800),
    },
}

# Security optimizations for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# File upload optimizations
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# session settings
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "sessions"

# Logging configuration for production
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": "logs/django.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

os.makedirs("logs", exist_ok=True)

# django-js-reverse configuration
JS_REVERSE_JS_VAR_NAME = "DjangoUrls"
JS_REVERSE_JS_MINIFY = True
JS_REVERSE_INCLUDE_ONLY_NAMESPACES = [
    "shared",
    "core",
    "media",
    "identity",
]


# JWT configuration
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=5),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "ninja_jwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "ninja_jwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    # For Controller Schemas
    # FOR SLIDING TOKEN
    "TOKEN_BLACKLIST_INPUT_SCHEMA": "ninja_jwt.schema.TokenBlacklistInputSchema",
    "TOKEN_VERIFY_INPUT_SCHEMA": "ninja_jwt.schema.TokenVerifyInputSchema",
}

# debug toolbar configuration
if not TESTING():
    INSTALLED_APPS.append(
        "debug_toolbar",
    )
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1"]
    DEBUG_TOOLBAR_PANELS = [
        "debug_toolbar.panels.history.HistoryPanel",
        "debug_toolbar.panels.versions.VersionsPanel",
        "debug_toolbar.panels.timer.TimerPanel",
        "debug_toolbar.panels.settings.SettingsPanel",
        "debug_toolbar.panels.headers.HeadersPanel",
        "debug_toolbar.panels.request.RequestPanel",
        "debug_toolbar.panels.sql.SQLPanel",
        "debug_toolbar.panels.staticfiles.StaticFilesPanel",
        "debug_toolbar.panels.templates.TemplatesPanel",
        "debug_toolbar.panels.alerts.AlertsPanel",
        "debug_toolbar.panels.cache.CachePanel",
        "debug_toolbar.panels.signals.SignalsPanel",
        "debug_toolbar.panels.redirects.RedirectsPanel",
        "debug_toolbar.panels.profiling.ProfilingPanel",
    ]

    DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": lambda request: SHOW_DEBUG_TOOLBAR}
